// Master reference lists extracted from Kréta template (OrarendImport_Sablon.xlsx)

export const KRETA_HETIREND_DEFAULT: string[] = [
  "Minden héten",
  "Szünet",
  "A hét",
  "B hét"
];

export const KRETA_NAP_DEFAULT: string[] = [
  "Hétfő",
  "Kedd",
  "Szerda",
  "Csütörtök",
  "Péntek",
  "Szombat",
  "Vasárnap"
];

export const KRETA_OSZTALY_DEFAULT: string[] = [
  "1. osztály",
  "10. Számítógépes-adatrögzítő",
  "10. Szobafestő",
  "2/A. osztály",
  "2/B. osztály",
  "3. osztály",
  "4. osztály",
  "5. osztály",
  "6/A. osztály",
  "6/B. osztály",
  "7. osztály",
  "8. osztály",
  "9. Családellátó",
  "9. Szobafestő",
  "9/E/A. osztály",
  "9/E/B. osztály",
  "Aut. Összevont",
  "Fejlesztő iskolai osztály",
  "Készségfejlesztő 11-12.",
  "Készségfejlesztő 9-10.",
  "Kollégium",
  "Óvoda",
  "Utazó Gyógypedagógiai Osztálya"
];

export const KRETA_CSOPORT_DEFAULT: string[] = [
  "1. osztály Napközis csoportja",
  "10. Számítógépes-adatrögzítő osztály Napközis csoportja",
  "10. Szobafestő Napközis csoportja",
  "2/A osztály Napközis csoportja",
  "2/B osztály A csoportja",
  "2/b osztály Napközis csoportja",
  "3. osztály Napközis csoportja",
  "4 osztály Napközis csoportja",
  "4. osztály A csoportja",
  "4. osztály B csoportja",
  "5. osztály Napközis csoportja",
  "6. osztály Napközis csoportja",
  "6/B. osztály napközis csoportja",
  "7. osztály Napközis csoportja",
  "8. osztály Napközis csoportja",
  "9. Családellátó osztály Napközis csoportja",
  "9. Szobafestő Napközis csoportja",
  "9/E/A. osztály Napközis csoportja",
  "9/E/B. osztály Napközis csoportja",
  "Autista összevont A csoportja",
  "Autista összevont B csoportja",
  "Autista összevont napközis csoportja",
  "Digitális kultúra",
  "Etika/Hit- és erkölcstan 1",
  "Etika/Hit- és erkölcstan 2",
  "Etika/Hit- és erkölcstan 3",
  "Etika/Hit- és erkölcstan 4",
  "Etika/Hit- és erkölcstan 5",
  "Etika/Hit- és erkölcstan 6",
  "Etika/Hit- és erkölcstan 7",
  "Etika/Hit- és erkölcstan 8",
  "Etika/Hit- és erkölcstan 9",
  "Etika/Hit- és erkölcstan csoport 12",
  "Etika/Hit- és erkölcstan csoport 13",
  "Etika/Hit- és erkölcstan csoport 14",
  "Etika/Hit- és erkölcstan csoport 15",
  "Etika/Hit- és erkölcstan csoport 16",
  "Etika/Hit- és erkölcstan csoport 17",
  "Etika/Hit- és erkölcstan csoport 19",
  "Etika/Hit- és erkölcstan csoport 20",
  "Fejlesztő Felkészítő csoport",
  "Fejlesztő Felkészítő csoport II.",
  "Gyógytestnevelés csoportja",
  "Készségfejlesztő 11 csoport",
  "Készségfejlesztő 11-12 A csoportja",
  "Készségfejlesztő 11-12 B csoportja",
  "Készségfejlesztő 12 csoport",
  "Készségfejlesztő 9-10/A csoport",
  "Készségfejlesztő 9-10/B csoport",
  "Kollégium I.",
  "Kollégium II.",
  "Kollégium III.",
  "Kollégium IV.",
  "Könyvtár csoport",
  "Labdarúgás",
  "Logopédiai ellátás",
  "Mozgásfejlesztés csoport (belső)",
  "Tánc",
  "Utazóbeszéd1-8Alsópáhok",
  "Utazóbeszéd1-8CsányBelvárosi",
  "Utazóbeszéd1-8Csány-Szendrey",
  "Utazóbeszéd1-8Egry",
  "Utazóbeszéd1-8Életfaiskola",
  "Utazóbeszéd1-8Gyenesdiás",
  "Utazóbeszéd1-8HévizIllyés",
  "Utazóbeszéd1-8Zalaapáti",
  "Utazóbeszéd1-8Zalaszántó",
  "Utazóbeszéd1-8Zöldmező",
  "UtazóbeszédoviAlsópáhok",
  "UtazóbeszédoviBalatongyörök",
  "UtazóbeszédoviCserszegtomaj",
  "UtazóbeszédoviDióskál",
  "UtazóbeszédoviÉletfa",
  "UtazóbeszédoviÉletfaGagarin",
  "UtazóbeszédoviÉletfaSopronuti",
  "UtazóbeszédoviÉletfaVörösmarti",
  "UtazóbeszédoviGyenesdiás",
  "UtazóbeszédoviHévíz",
  "UtazóbeszédoviKarmacs",
  "UtazóbeszédoviNemesbük",
  "UtazóbeszédoviRezi",
  "UtazóbeszédoviSármellék",
  "UtazóbeszédoviVonyarc",
  "UtazóbeszédoviZalaapáti",
  "UtazóbeszédoviZöldmező",
  "utazóért1-8Életfaiskola",
  "Utazóért1-8Zalaszántó",
  "utazóértoviBalatongyörök",
  "UtazóértoviDióskál",
  "UtazóértoviÉletfa",
  "UtazóértoviÉletfaGagarin",
  "UtazóértoviÉletfaSopron",
  "UtazóértoviGyenesdiás",
  "UtazóértoviHévíz",
  "UtazóértoviSármellék",
  "UtazóértoviVonyarcvashegy",
  "UtazóértoviZalaapáti",
  "UtazóértoviZalacsány",
  "Utazópszich1-8Alsópáhok",
  "Utazópszich1-8Egry",
  "Utazópszich1-8Gyenesdiás",
  "Utazópszich1-8Hévíz",
  "UtazópszichoviAlsópáhok",
  "Utazópszichovicserszegtomaj",
  "UtazópszichoviÉletfaVörösmarty",
  "UtazópszichoviKarmacs",
  "UtazópszichoviNemesbük",
  "UtazópszichoviRezi",
  "UtazópszichoviVárvölgy",
  "Zenei nevelés"
];

export const KRETA_TANTARGY_DEFAULT: string[] = [
  "A külső világ tevékeny megismerése",
  "A pályaorientáció",
  "Ábrázolás-alakítás",
  "Állampolgári ismeretek",
  "Állampolgárságra, demokráciára nevelés",
  "Általános vállalkozási ismeretek",
  "Angol nyelv",
  "Angol nyelv/Kommunikáció",
  "Anyagvizsgálatok gyakorlat",
  "Anyanyelvi nevelés",
  "Ápolási gondozási gyakorlatok",
  "Atlétika",
  "Az erkölcsi nevelés",
  "Az önismeret és a társas kultúra fejlesztése",
  "Beszédfejlesztés",
  "Beszélgetőkör",
  "Beton és vasbeton szerkezetek",
  "Beton és vasbeton szerkezetek gyakorlat",
  "Család- és háztartás-ellátási gyakorlat",
  "Családellátás - gondozás",
  "családellátás,- gondozás",
  "Családellátás, gondozás",
  "Család-és háztartás-ellátási gyakorlat16",
  "Családi életre nevelés",
  "Digitális kultúra",
  "Díszítőmunkák, szakrajz, színelmélet",
  "Egybefüggő szakmai gyakorlat",
  "Egyéni fejlesztés",
  "Élelmiszerek és táplálkozási , étkezési alapismeretek",
  "Élelmiszerek és táplálkozási, ételkészítési alapismeretek",
  "Életvitel és gyakorlat",
  "Elsősegélynyújtás gyakorlat",
  "Ének-zene",
  "Ének-zene énekes játék, gyermektánc",
  "Ének-zene, énekes játék, gyermektáncok",
  "Építőipari alapismeretek",
  "Építőipari alapismeretek gyakorlat",
  "Építőipari kivitelezési alapismeretek gyakorlat",
  "Építőipari rajzi alapismeretek",
  "Épületlakatos feladatok gyakorlata",
  "Épületlakatos ismeretek",
  "Erkölcsi nevelés",
  "Érzékelés - észlelés és értelem fejlesztés",
  "Etika/Hit- és erkölcstan",
  "Falazás, vakolás",
  "Falazás, vakolás gyakorlat",
  "Falfelület festése diszítése",
  "Falfelület festésének, díszítésének gyakorlata",
  "Fejlesztő felkészítés",
  "Fejlesztő felkészítés /AD/",
  "Fejlesztő felkészítés Cserszeg",
  "Felelősségvállalás másokért, önkéntesség",
  "Felelősségvállalás-önkéntesség",
  "Fenntarthatóság, környezettudatosság",
  "Fenntarthatóság-környezettudatosság",
  "Fenntarthatóség, környezettudatosság",
  "Foglalkoztatás I",
  "Foglalkoztatás I.",
  "Foglalkoztatás II",
  "Foglalkoztatás II.",
  "Földrajz",
  "Gazdasági és pénzügyi nevelés",
  "Gazdasági és pénzüögyi kultúra",
  "Gépészeti alapozó feladatok",
  "Gépészeti feladatok elmélet",
  "Gépészeti feladatok gyakorlata",
  "Gépészeti kötések alapjai",
  "Gépészeti kötések készítésének gyakorlata",
  "Gépírás és levelezési gyakorlat",
  "Gyakorlat",
  "Gyakorlati képzés előkészítése",
  "Gyakorlati képzés előkészítő",
  "Gyakorlat-termesztési ismeretek",
  "Gyógytestnevelés",
  "Gyógytorna",
  "Hab.integráltan nem oktatható",
  "Habilitáció integráltan nem oktatható 12",
  "Habilitáció-rehabilitáció",
  "Habilitáció-rehabilitáció (mese)",
  "Habilitáció-rehabilitáció mese",
  "Habilitáciő integráltan nem oktatható 11",
  "Habilitáci-rehabiltáció",
  "Habiltáció-rehbilitáció",
  "Hangszer szakkör",
  "Háztartástan",
  "Háztartástan 12",
  "Háztartástan és életvitel",
  "Higiénie",
  "Hon- és népismeret",
  "Hon-és népismeret",
  "Idegen nyelv",
  "Információs eszközök használata",
  "Informatika",
  "Informatikai eszközök használata",
  "Integráltan nem oktatható habilitációs-rehabilitációs foglalkozás",
  "Irodai alkalmazások gyakorlata",
  "Iskolapszichológia",
  "Játékra nevelés",
  "Kert- és parkápoló",
  "Kert- és parkápoló 11",
  "Kert- és parkápoló12",
  "Kertfenntartás",
  "Kertfenntartás gyakorlat",
  "Kertfenntartás műszaki ismeretei",
  "Kertfenntartás műszaki ismeretei gyakorlat",
  "Kertfenntartási műszaki ismereti gyakorlat",
  "Kiegészítő kőműves feladatok",
  "Kiegészítő kőműves feladatok gyakorlat",
  "Kiegészítő kőműves gyakorlat",
  "Kollégiumi foglalkozás",
  "Kommunikáció",
  "Kommunikáció a titkári munkában",
  "Komplex fejlesztés",
  "Komplex gyógypedagógiai-logopédiai fejlesztés",
  "Komplex logopédiai és gyógypedagógiai fejlesztés",
  "Konyhai munkák, ételkészítési alapgyakorlatok",
  "Korrózió elleni védelem",
  "Könyvtári óra",
  "Könyvtári órák",
  "Környezet és egészségvédelem",
  "Környezet- és egészségvédelem",
  "Környezetismeret",
  "Közösségi nevelés",
  "Külső világ, tevékeny megismerése",
  "Lakástextíliák gyártástechnológiája",
  "Lakástextíliák készítése, javítása - gyakorlat",
  "Lakástextíliák készítése, javítása gyakorlat",
  "Lakókörnyezet gondozási és ruhaápolási gyakorlatok",
  "Lakókörnyezet kialákítása",
  "Lakókörnyezet-kialakítás",
  "Lego",
  "Logopédia",
  "Magasban végzett lakatos feladatok",
  "Magyar nyelv és irodalom",
  "Matematika",
  "Médiatudatosságra nevelés",
  "Mézeskalács",
  "Mézeskalács sütő",
  "Mozgás",
  "Mozgás nevelés",
  "Mozgásfejlesztés",
  "Mozgásfejlesztés(TSMT)",
  "Mozgásnevelés",
  "Munka- és környezetvédelem",
  "Munka- és környezetvédelem gyakorlat",
  "Munkahelyi egészség és biztonság",
  "Munkavállalói idegen nyelv",
  "Munkavállalói ismeretek",
  "Munkavédelem",
  "Munkavédelem, munkahelyi egészség és biztonság",
  "Műszaki alapismeret gyakorlat",
  "Műszaki alapismeretek",
  "Műszaki alapismeretek gyakorlat",
  "Műszaki ismeretek",
  "Műszaki ismeretek gyakorlat",
  "Műszaki rajz, vizuális nevelés",
  "Napközi",
  "Nemzeti öntudat és hazafias nevelés",
  "Nemzeti öntudat, hazafias nevelés",
  "Növényismeret",
  "Növényismeret gyakorlat",
  "Növénytan",
  "Nyelv és beszédfejlesztés",
  "Olvasás -írás",
  "Olvasás-írás",
  "Osztályfőnöki",
  "Osztályfőnöki (közösségi nevelés)",
  "Osztályfőnöki óra",
  "Osztályfőnöki óra (Közösségi nevelés)",
  "Óvodai fejlesztés",
  "Önismeret és társas kultúra fejlesztése",
  "Önkiszolgálás",
  "Önkiszolgálás, egészséges életmódra nevelés",
  "Önkiszolgálásra nevelés",
  "Pályaorientáció",
  "Parkfenntartás",
  "Parkfenntartás gyakorlat",
  "Pénzügyi kultúra adaptálása",
  "Rajz",
  "Rajzolás, festés, mintázás, kézimunka",
  "Reggeli kör",
  "Reggeli köszöntő kör",
  "Reggeli köszöntőkör",
  "Ruhaipari anyag és áruismeret",
  "Ruhaipari anyag- és áruismeret",
  "Ruhaipari anyag-és áruismeret",
  "Ruhaipari gépek üzemeltetése",
  "Ruhaipari gyártás-előkészítés",
  "Szabad játék",
  "Szakmai alapozó ismeretek",
  "Szakmai elmélet beton és vasbeton szerkezetek",
  "Szakmai elmélet építőipari alapismeretek",
  "Szakmai elmélet épületlakatos feladatok",
  "Szakmai gyakorlat (egészségügy)",
  "Szakmai Gyakorlat (Építőipar)",
  "Szakmai gyakorlat (informatika)",
  "szakmai gyakorlat (könnyűipar)",
  "Szakmai Gyakorlat (Mezőgazdaság)",
  "Szakmai gyakorlat épületlakatos gyakorlat",
  "Szakmai gyakorlat hab. rehab.",
  "Szakmai gyakorlat kertfenntartáas műszaki ismeretei gyakorlat",
  "Szakmai gyakorlat kertfenntartás gyakorlat",
  "Szakmai gyakorlat mézeskalács készítés",
  "szakmai gyakorlat növényismeret gyakorlat",
  "Szakmai gyakorlat szerkezetlakatos feladatok gyakorlata",
  "Szakmai gyakorlat szövés",
  "Szakmai gyakorlat termesztési ismeretek gyakorlat",
  "Szakmai számítás",
  "Számítógépes ruhaipari gyártás-előkészítés gyakorlat",
  "Számolás-mérés",
  "Szekezetlakatos feladatok",
  "Szerkezetlakatos feladatok",
  "Szerkezetlakatos feladatok gyakorlata",
  "Szigetelés",
  "Szigetelés gyakorlat",
  "Szivacs kézilabda",
  "Szövés",
  "Szövés 11",
  "Szövés 12",
  "Szövött tárgy készítő",
  "Szűkebb - tágabb környezet",
  "Szűkebb- tágabb környezet",
  "Szűkebb-tágabb környezet",
  "Tánc",
  "Tanórán kívüli foglalkozás",
  "Tanulás tanítása",
  "Tanulószoba",
  "Tapétázási munkák",
  "Tapétázási munkák gyakorlat",
  "Társadalmi ismeretek",
  "Technika és tervezés",
  "Technika, életvitel és gyakorlat",
  "Technológia, anyagismeret",
  "Technológia, anyagismeret gyakorlat",
  "Térburkolás",
  "Térburkolás gyakorlat",
  "Természetismeret",
  "Természettudomány",
  "Termesztési ismeretek",
  "Termesztési ismeretek gyakorlat",
  "Testépítés",
  "Testi és lelki egészségre nevelés",
  "Testi, lelki egészség",
  "Testnevelés",
  "Testnevelés és sport",
  "Textiltermékek gyártástechnológiája",
  "Textiltermékek készítése gyakorlat",
  "Textiltermékek szabásmintakészítése",
  "Textiltermékek szabásminta-készítése",
  "Történelem",
  "Történelem, társadalmi és állampolgári ismeretek",
  "TSMT",
  "Udvari játék",
  "Udvaros 11",
  "Vállalkozási ismeretek",
  "Vegyes kőműves feladatok",
  "Verselés, mesélés",
  "Víz-, hő- és hangszigetelés",
  "Vizuális kultúra",
  "Vizuomotoros",
  "Vizuomotoros készség fejlesztése",
  "Zenei nevelés",
  "Zenei nevelés alapjai"
];

export const KRETA_TANAR_DEFAULT: string[] = [
  "[BTA 5] Betöltetlen gyógypedagógus",
  "[BTA 6] gyógypedagógus",
  "[HO 1] Hittan Oktató",
  "[KA 1] Dr. Pintér Csaba Lászlóné",
  "[KA 2] Pohl Lenke",
  "Ádovics-Andorkó Veronika",
  "Bagarus Viktória",
  "Bányai Zita Csilla",
  "Barnáné Szodorai Mária",
  "Bodnár Orsolya",
  "Bokor-Krokker Kornélia",
  "Borbás Andrea",
  "Budai Péter",
  "Budainé Molnár Mária Márta",
  "Csala Tamás",
  "Csehné Farkas Andrea",
  "Cseke Krisztina",
  "Csima Annamária",
  "Csitári Ibolya",
  "Dénesné Rosta Krisztina",
  "Domokos Hajnalka",
  "Dr. Pribék Dalma",
  "Faragó Dorina",
  "Fekete Ferencné",
  "Gál-Ajtai Edit Ilona",
  "Gede Zsófia",
  "Gönczi Emese Mária",
  "Gudics Péter",
  "Gulyás Andrea",
  "Hajasné Léránt Zsófia",
  "Halász Cintia Katalin",
  "Horváth Klára",
  "Horváth Róbert",
  "Husonyiczáné Orosz Andrea",
  "Huszárik Zita",
  "Huszárné Györek Katalin",
  "Illésné Bedő Mónika",
  "Jakabfi-Guzmics Anna",
  "Jaksa Péterné",
  "Katona-Németh Mónika",
  "Kirilla Valéria",
  "Kis Zoltánné",
  "Kis-Móró Tamara",
  "Kissné Debre Jolán",
  "Kocsis Judit",
  "Kocsis Lajosné",
  "Kocsmár Anita",
  "Kollár-Pénzes Adrienn",
  "Kollerné Horváth Adrienn",
  "Kovács Aliz",
  "Krasznai Tamásné",
  "Lass Ilona Judit",
  "Lénárt Maria Christina",
  "Liszákné Jakab Renáta",
  "Lóki-Gróf Alexandra Erzsébet",
  "Magné Mórocz Cecília",
  "Magyarosi Etelka",
  "Markielné Mészáros Márta",
  "Marton Ágnes",
  "Máté István",
  "Móróné Berta Anita",
  "Nagy Sándor",
  "Németh Brigitta",
  "Németh Jánosné",
  "Németh Zsófia",
  "Oláh Gabriella",
  "Pálmai Melinda",
  "Pimper Klaudia",
  "Rajky Ágota Annamária",
  "Rajnai Laura",
  "Salamon Andrea",
  "Schinkovics Krisztina",
  "Seffer Gábor",
  "Soltész Adrien Éva",
  "Somogyi Lívia",
  "Szabó Árpádné",
  "Szabó Imre",
  "Szakonyi Judit",
  "Szántó István",
  "Szelencsik Gábor",
  "Szitáné Sütő Andrea",
  "Takácsné Cserti Éva Mónika",
  "Tordáné Lukács Ágnes",
  "Tóth Alexandra",
  "Tóth Enikő",
  "Tóth Krisztina",
  "Tömör-Tihanyi Erika",
  "Tuboly Bernadett",
  "Varnava Krisztina",
  "Vasvári Virág",
  "Vincze Beáta",
  "Voltnerné Rudolf Anita",
  "Zimmerman-Cintián Anasztázia"
];

export const KRETA_HELYISEG_DEFAULT: string[] = [
  "1. b osztály",
  "1. osztály",
  "2. osztály",
  "3. osztály",
  "4. osztály",
  "5. a. osztály",
  "5. b. osztály",
  "5. osztály",
  "6. osztály",
  "7. osztály",
  "8. osztály",
  "9/e osztály",
  "Autista csoport",
  "Beszédfejlesztés csoport",
  "Családellátó",
  "Egyéb külső helyszín",
  "Fejlesztő iskolai osztály",
  "Fejlesztő terem",
  "Festő gyakorlati hely",
  "Gyakorló konyha",
  "Informatikai terem",
  "Iskolai pszichológiai terem",
  "Készségfejlesztő 11-12",
  "Készségfejlesztő 9-10",
  "Kollégium",
  "Konditerem",
  "Könyvtár",
  "Óvodai csoportszoba",
  "Parkgondozó osztály",
  "Számítógépes adatrögzítő osztály",
  "Szobafestő",
  "Textiltermék összeállító osztály",
  "Tornaterem",
  "Udvari sportpálya",
  "Uszoda",
  "Varroda"
];
